# Generated by Django 3.2.5 on 2021-08-06 17:33

from django.db import migrations
from django.contrib.auth.hashers import make_password
from users.models import User
from agenda.models import Cidadao, AgendamentoVacinacao


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210731_1629'),
        ('agenda', '0005_agendamentovacinacao_cidadao')
    ]

    def popular_banco(apps, schema_editor):
       user1 =User.objects.create(name='lucas', email='lucas@localhost', password=make_password("123456") )
       cidadao1 = Cidadao.objects.create(user=user1, nome_completo='Lucas Nóbrega', data_nascimento='1999-05-01')
       user2 =User.objects.create(name='pedro', email='pedro@localhost', password=make_password("123456") )
       cidadao2 = Cidadao.objects.create(user=user2, nome_completo='Pedro Silva', data_nascimento='1996-07-05')
       user3 =User.objects.create(name='paulo', email='paulo@localhost', password=make_password("123456") )
       cidadao3 = Cidadao.objects.create(user=user3, nome_completo='Paulo Silva', data_nascimento='1996-07-05')
       user4 =User.objects.create(name='joao', email='joao@localhost', password=make_password("123456") )
       cidadao4 = Cidadao.objects.create(user=user4, nome_completo='João Silva', data_nascimento='1996-07-05')

    operations = [
       migrations.RunPython(popular_banco),
    ]
