@hostname = localhost
@api_versao = v1 
@porta = 8000
@protocolo = http
@base_url = {{protocolo}}://{{hostname}}:{{porta}}
@api_url = {{base_url}}/api/{{api_versao}}
@auth_url =  {{base_url}}/oauth2

###
GET {{api_url}}/grupo-atendimento

###*
GET {{api_url}}/local-vacinacao

###
GET {{api_url}}/cidadao

### Cadastro de usuario
# @name cadastroUsuario
POST {{base_url}}/cadastro/
content-type: application/json

{
   "email" : "joaopedroalubefrto@localhost",
   "password" : "teste123",
   "password2" : "teste123",
   "data_nascimento" : "2021-08-03",
   "nome_completo": "Pedro da Silva"
}


### Atenticar o admin utilizando JWT
# @name login
POST {{base_url}}/api/token/ HTTP/1.1
content-type: application/json

{
   "email": "{{$dotenv DJANGO_ADMIN_EMAIL}}", 
   "password": "{{$dotenv DJANGO_ADMIN_PASSWORD}}"
}


### Requisitar conteúdo restrito com token obtido no login
@authToken = {{login.response.body.access}}
@refreshToken = {{login.response.body.refresh}}
GET {{base_url}}/api/v1/
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Logout invalidando o Token
POST {{base_url}}/api/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "refresh_token" : "{{refreshToken}}"
}


### Atenticar o usuario utilizando JWT
# @name loginUsuario
POST {{base_url}}/api/token/ HTTP/1.1
content-type: application/json

{
   "email": "{{$dotenv USER_TESTE_EMAIL}}", 
   "password": "{{$dotenv USER_TESTE_PASSWORD}}"
}

### Pegar dados do usuário logado
# @name dadosUsuarioLogado
@authTokenUsuario = {{loginUsuario.response.body.access}}
GET {{base_url}}/api/verlogin/
Content-Type: application/json
Authorization: Bearer {{authTokenUsuario}}

###
# @name pegarPrimeiroGrupo
GET {{api_url}}/grupo-atendimento
Content-Type: application/json


###
@authTokenUsuario = {{loginUsuario.response.body.access}}
@idCidadao = {{dadosUsuarioLogado.response.body.cidadao_id}}
@idPrimeiroGrupo = {{pegarPrimeiroGrupo.response.body.$[0].grupo_id}}
POST {{base_url}}/api/v1/agendamento-vacinacao/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{authTokenUsuario}}

{
   "status": 1, 
   "hora": "10:22:00",
   "data": "2021-08-11",
   "cidadao": "{{idCidadao}}", 
   "grupo_atendimento": "{{idPrimeiroGrupo}}",
   "local_vacinacao": "2546930"
}

### Pegar locais próximos
GET {{api_url}}/local-vacinacao-proximos/?latitude=-5.5193682&longitude=-47.5129447&proximidade=5

###
GET {{base_url}}/api/v1/agendamento-vacinacao/6bca8cb2-332f-4478-a40a-ade2186acb03 
### Pegar locais
GET {{api_url}}/local-vacinacao/203949445

### Cadastrando Local de Vacinação
@authTokenAdmin = {{login.response.body.access}}
POST {{base_url}}/api/v1/local-vacinacao/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
   "vlr_latitude": 5.51,
   "vlr_longitude": 50.0,
   "cod_munic": "2408102",
   "cod_cnes": "123456896834236",
   "nom_estab": "teste",
   "dsc_endereco": "testando",
   "dsc_bairro": "testando",
   "dsc_cidade": "testando"
}

### Editar Local de Vacinação
@authTokenAdmin = {{login.response.body.access}}
PUT {{base_url}}/api/v1/local-vacinacao/12345689683423654/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
   "vlr_latitude": 65.0,
   "vlr_longitude": 72.0,
   "cod_munic": "2408102",
   "cod_cnes": "123456896834236",
   "nom_estab": "Centro de Saúde Popular",
   "dsc_endereco": "Rua Estreita n. 01",
   "dsc_bairro": "Vila Lobão",
   "dsc_cidade": "Imperatriz"
}

### Pegar agendamento do usuario logado
@authTokenUsuario = {{loginUsuario.response.body.access}}
GET {{api_url}}/agendamento-vacinacao/
content-type: application/json
Authorization: Bearer {{authTokenUsuario}}

### Pegar agendamento do usuario admin
@authTokenAdmin = {{login.response.body.access}}
GET {{api_url}}/agendamento-vacinacao/
content-type: application/json
Authorization: Bearer {{authTokenAdmin}}

### Cancelar um agendamento do usuário
@authTokenUsuario = {{loginUsuario.response.body.access}}
POST  {{api_url}}/agendamento-vacinacao/0c34db93-1b4b-4b88-9623-aa7986af8934/cancelar/
content-type: application/json
Authorization: Bearer {{authTokenUsuario}}

### Cancelar um agendamento que não é do usuário (Erro esperado)
@authTokenUsuario = {{loginUsuario.response.body.access}}
POST {{api_url}}/agendamento-vacinacao/f8cafc76-dbf9-4e8d-8d8b-a013d38217cb/cancelar/
content-type: application/json
Authorization: Bearer {{authTokenUsuario}}


###
@authTokenAdmin = {{login.response.body.access}}
//@idCidadao = {{dadosUsuarioLogado.response.body.cidadao_id}}
//@idPrimeiroGrupo = {{pegarPrimeiroGrupo.response.body.$[0].grupo_id}}
DELETE {{base_url}}/api/v1/cidadao/6e4ae566-a503-458f-9cf9-4cf1037b3c5e/ HTTP/1.1
content-type: application/json
Authorization: Bearer {{authTokenAdmin}}

###
GET {{api_url}}/agendamento-vacinacao/estatistica
