# Generated by Django 3.2.5 on 2021-07-28 01:40

from django.db import migrations
from agenda.models import GrupoAtendimento

def popularGrupoAtendimento(apps, schema_editor):
    GrupoAtendimento.objects.create(nome='Grupo 1', idade_minima=65)
    GrupoAtendimento.objects.create(nome='Grupo 2', idade_minima=60)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popularGrupoAtendimento),
        
    ]