# Generated by Django 3.2.5 on 2021-07-28 01:40

from django.db import migrations
from agenda.models import LocalVacinacao
import csv


def carregaLocaisVacinacao(apps, schema_editor):
   with open('datasets/ubs.csv', newline='', encoding="utf8") as csvfile:
      locais = csv.DictReader(csvfile)
      for local in locais:
         local = LocalVacinacao.objects.get_or_create(
            vlr_latitude = local["vlr_latitude"],
            vlr_longitude = local["vlr_longitude"],
            cod_munic = local["cod_munic"],
            cod_cnes = local["cod_cnes"],
            nom_estab = local["nom_estab"],
            dsc_endereco = local["dsc_endereco"],
            dsc_bairro = local["dsc_bairro"],
            dsc_cidade = local["dsc_cidade"],
         )

class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_localvacinacao')
        
    ]

    operations = [
       migrations.RunPython(carregaLocaisVacinacao),
    ]

