# Generated by Django 3.2.5 on 2021-07-31 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0004_carrega_locais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('cidadao_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('nome', models.CharField(max_length=254, null=True)),
                ('data_nascimento', models.CharField(max_length=30, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoVacinacao',
            fields=[
                ('status', models.IntegerField(choices=[(1, 'Agendado'), (2, 'Cancelado'), (3, 'Vacinado')], default=1)),
                ('agendamento_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('data', models.DateField()),
                ('idade', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.cidadao')),
                ('grupo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.grupoatendimento')),
                ('local_vacinacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.localvacinacao')),
            ],
        ),
    ]
