# Generated by Django 3.2.5 on 2021-07-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20210731_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
